[project]
name = "rato-fast-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "brm-dev.ai", email = "contato@brunoradames.com.br" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
rato-fast-api = "rato_fast_api:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
